name: the_reader
description: A premium Manga & Manhwa reader with Liquid Glass aesthetic.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^13.0.0

  # Local Storage
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  # UI
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0

  # Utils
  uuid: ^4.2.2
  intl: ^0.19.0
  path_provider: ^2.1.2
  http: ^1.1.0

  # Icons
  cupertino_icons: ^1.0.6
  html: ^0.15.6
  webview_windows: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
